(ns plato.example.core
  (:require [plato.core :as plato]
            [plato.deck :as deck]
            [plato.desargues :as desargues]))

(def animation-graph
  {:scene :plato-demo
   :nodes
   {1 {:id 1 :node :text :text "Desargues scene graph"
       :at [0 2.6] :opts {:font-size 34 :color :white :weight "BOLD"}}
    2 {:id 2 :node :circle :at [-3 0]
       :opts {:radius 1.15 :color :teal}
       :fill {:color :teal :opacity 0.25}
       :stroke {:color :teal :width 4}}
    3 {:id 3 :node :decimal :value 100 :at [-3 0]
       :opts {:font-size 38 :color :white :num-decimal-places 0}}
    4 {:id 4 :node :text :text "Pure data → live SVG"
       :at [2.2 0] :opts {:font-size 30 :color :gold}}}
   :steps
   [{:step :play
     :anims [{:anim :appear :target 1 :opts {:run-time 0.7}}
             {:anim :draw :target 2 :opts {:run-time 1.0}}]}
    {:step :play
     :anims [{:anim :appear :target 3 :opts {:run-time 0.5}}
             {:anim :appear :target 4 :opts {:run-time 0.5}}]}
    {:step :play
     :anims [{:anim :count-to :target 3 :value 500
              :opts {:run-time 1.5}}
             {:anim :emphasize :target 4 :opts {:run-time 1.5}}]}
    {:step :play
     :anims [{:anim :glide :target 2 :to [-1.1 0]
              :opts {:run-time 1.2}}
             {:anim :glide :target 3 :to [-1.1 0]
              :opts {:run-time 1.2}}]}
    {:step :hold :seconds 1.0}]})


(def layout-graph
  {:scene :layout-demo
   :kind :layout
   :nodes
   {1 {:node :text
       :id 1
       :content "Plato"
       :box {:x 5.851911 :y 0.5 :w 1.5184 :h 0.6716}
       :style {:font-size 40 :color :gold}}
    2 {:node :text
       :id 2
       :content "Desargues layout → browser"
       :box {:x 4.550359 :y 1.1716 :w 4.121504 :h 0.40296}
       :style {:font-size 24 :color :white}}}
   :steps
   [{:step :play
     :anims [{:anim :appear :target :scene :ids [1 2] :opts {}}]}
    {:step :hold :seconds 1.0}]
   :layout
   {:desargues.layout/box {:x 0 :y 0 :w 13.222222 :h 7.0}}})

(def model
  (deck/deck
   {:title "Plato"
    :config {:hash true
             :history true
             :controls true
             :progress true
             :center true
             :transition :slide}
    :slides
    [(deck/slide
      :welcome
      [:div
       [:div.plato-kicker "ClojureScript presentation engine"]
       [:h1 "Plato"]
       [:p "Reveal.js navigation. Immutable deck data. Live Desargues animation."]
       [:p.fragment "Slides become programs without becoming a JavaScript project."]]
      {:background-color "#0b0e13"
       :notes "Open speaker view with S. Overview with O."})

     (deck/slide
      :capabilities
      [:div
       [:div.plato-kicker "One composition model"]
       [:h2 "Better primitives above Reveal"]
       [:div.plato-grid
        [:div.plato-card.fragment
         [:h3 "Data"]
         [:p "Decks, stacks, slides, fragments and notes are Clojure values."]]
        [:div.plato-card.fragment
         [:h3 "Animation"]
         [:p "Desargues RecordingBackend graphs compile into scrub-able SVG timelines."]]
        [:div.plato-card.fragment
         [:h3 "Extension"]
         [:p "Protocols and multimethods keep render targets and node kinds open."]]]])

     (deck/slide
      :animation
      (desargues/scene animation-graph {:controls? true :autoplay? true})
      {:transition :fade
       :notes "This graph has the same :scene/:nodes/:steps shape emitted by Desargues."})

     (deck/slide
      :layout
      (desargues/scene layout-graph {:controls? true :autoplay? true})
      {:transition :fade
       :notes "Generated by Desargues render-layout! through RecordingBackend."})

     (deck/stack
      :deep-dive
      [(deck/slide
        :markdown
        "# Markdown is native\n\n- Reveal plugins remain available\n- Code highlighting, math, notes and search\n- Horizontal and vertical navigation")
       (deck/slide
        :math
        [:div
         [:div.plato-kicker "Reveal math plugin"]
         [:h2 "\\[ e^{i\\pi} + 1 = 0 \\]"]
         [:p.fragment "Clojure data can contain ordinary HTML, components, or Desargues scenes."]])])

     (deck/slide
      :finish
      [:div
       [:div.plato-kicker "Plato"]
       [:h2 "Author once. Present anywhere."]
       [:p "Press F for fullscreen, O for overview, S for speaker notes, and ? for shortcuts."]]
      {:background-color "#111827"})]}))

(defn- root [] (js/document.getElementById "app"))

(defn init []
  (plato/mount! (root) model))

(defn ^:dev/after-load remount!
  "Shadow hot-reload hook: tear the deck down and rebuild it, so an edit to the
   deck value shows without a page refresh. Reveal is destroyed on unmount, so
   the reload leaves no second instance behind."
  []
  (let [el (root)]
    (plato/unmount! el)
    (plato/mount! el model)))
