;; Generate src/plato/nfd.cljc — the canonical decomposition table plato uses
;; on every dialect. Run: clojure -M scripts/gen-nfd.clj
;;
;; The JVM is the oracle here: each entry is exactly what java.text.Normalizer
;; produces for that character, and plato.nfd-test re-checks that.
(ns gen-nfd
  (:require [clojure.string :as str])
  (:import [java.text Normalizer Normalizer$Form]))

(def ranges
  "[lo hi label] blocks whose precomposed characters the table covers."
  [[0x00C0 0x024F "Latin-1 Supplement, Latin Extended-A and -B"]
   [0x0370 0x03FF "Greek and Coptic"]
   [0x0400 0x04FF "Cyrillic"]
   [0x1E00 0x1EFF "Latin Extended Additional"]
   [0x1F00 0x1FFF "Greek Extended"]])

(defn nfd [^String s] (Normalizer/normalize s Normalizer$Form/NFD))

(defn entries []
  (for [[lo hi] ranges
        cp (range lo (inc hi))
        :let [s (str (char cp)) d (nfd s)]
        :when (not= s d)]
    (str s d)))

(defn escape [s] (apply str (map #(format "\\u%04X" (int %)) s)))

(defn source []
  (let [es (entries)
        rows (partition-all 4 es)]
    (str "(ns plato.nfd\n"
         "  \"GENERATED by scripts/gen-nfd.clj. Do not edit; run `npm run nfd`.\n\n"
         "   Canonical decompositions for the precomposed characters of "
         (str/join ", " (map #(nth % 2) ranges)) ".\n"
         "   Each entry is one composed character followed by its NFD expansion.\")\n\n"
         "(def blocks\n"
         "  \"[lo hi label] Unicode blocks the table covers, as codepoints.\"\n"
         "  [" (str/join "\n   " (map (fn [[lo hi label]]
                                       (format "[0x%04X 0x%04X \"%s\"]" lo hi label))
                                     ranges))
         "])\n\n"
         "(def ^:private packed\n"
         "  [" (str/join "\n   " (map (fn [row]
                                        (str/join " " (map #(str "\"" (escape %) "\"") row)))
                                      rows))
         "])\n\n"
         "(def table\n"
         "  \"Composed character -> its NFD expansion.\"\n"
         "  (into {} (map (fn [e] [(first e) (subs e 1)])) packed))\n")))

(defn -main [& _]
  (spit "src/plato/nfd.cljc" (source))
  (println "wrote src/plato/nfd.cljc —" (count (entries)) "entries"))

(-main)
