#!/usr/bin/env bash
#
# Install `plato` from THIS checkout, without Homebrew.
#
#   scripts/install.sh                 # JVM launcher over this working tree
#   scripts/install.sh --native        # the ClojureWasm binary, if it is built
#   scripts/install.sh --prefix ~/.opt # somewhere other than ~/.local
#   scripts/install.sh --uninstall
#
# The Homebrew formula (buddhilw/tap/plato) installs a PINNED tag and is what a
# deck author elsewhere should use. This script is the other half: it installs
# the code in front of you, so an edit to src/ changes the next `plato` run with
# no reinstall step. The two are deliberately different in that one respect and
# identical in every other, launcher shape included.
#
# Two modes, and the difference is what they point at:
#
#   default   a shell launcher that runs `clojure -Sdeps {:local/root <here>}`.
#             Always available, starts a JVM, and tracks the working tree.
#   --native  copies the self-contained binary scripts/build-cli.sh produces
#             with ClojureWasm. No JVM at run time; it is a SNAPSHOT, so it
#             stops tracking the tree the moment you edit src/.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PREFIX="${PLATO_PREFIX:-$HOME/.local}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
THEMES="$XDG_DATA_HOME/plato/themes"
MODE="launcher"

while [ $# -gt 0 ]; do
  case "$1" in
    --native)    MODE="native"; shift ;;
    --uninstall) MODE="uninstall"; shift ;;
    --prefix)    PREFIX="$2"; shift 2 ;;
    --prefix=*)  PREFIX="${1#*=}"; shift ;;
    -h|--help)   sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *)           echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

BIN="$PREFIX/bin/plato"

if [ "$MODE" = "uninstall" ]; then
  rm -f "$BIN"
  # Only remove the theme link if it points HERE. A copy, or a link into some
  # other plato, belongs to whoever put it there.
  if [ -L "$THEMES" ] && [ "$(readlink "$THEMES")" = "$ROOT/theme" ]; then
    rm -f "$THEMES"
    echo "removed $THEMES"
  fi
  echo "removed $BIN"
  exit 0
fi

# The shared theme root that a deck's `:extends "plato.tokens.edn"` resolves
# against when it is not resolved relative to the deck. A LINK rather than a
# copy, so editing theme/plato.tokens.edn here is visible immediately, which is
# the entire point of a local install.
mkdir -p "$(dirname "$THEMES")"
if [ -e "$THEMES" ] && [ ! -L "$THEMES" ]; then
  THEME_NOTE="themes:    $THEMES (left alone: it exists and is not a symlink)"
else
  ln -sfn "$ROOT/theme" "$THEMES"
  THEME_NOTE="themes:    $THEMES -> $ROOT/theme"
fi

mkdir -p "$PREFIX/bin"

if [ "$MODE" = "native" ]; then
  [ -x "$ROOT/dist/plato" ] || {
    echo "dist/plato is not built. Run: scripts/build-cli.sh" >&2
    exit 1
  }
  install -m 0755 "$ROOT/dist/plato" "$BIN"
  echo "installed $BIN (native snapshot, $(wc -c < "$BIN") bytes)"
else
  command -v clojure >/dev/null || { echo "the Clojure CLI is required" >&2; exit 1; }
  cat > "$BIN" <<SH
#!/usr/bin/env bash
# Generated by plato's scripts/install.sh. Do not edit.
# Runs the working tree at $ROOT, so edits there take effect with no reinstall.
set -euo pipefail
export XDG_DATA_HOME="\${XDG_DATA_HOME:-\$HOME/.local/share}"
exec clojure -Sdeps '{:deps {io.github.BuddhiLW/plato {:local/root "$ROOT"}}}' \\
  -M -m plato.cli "\$@"
SH
  chmod 0755 "$BIN"
  echo "installed $BIN (launcher over $ROOT)"
fi

echo "$THEME_NOTE"
case ":$PATH:" in
  *":$PREFIX/bin:"*) ;;
  *) echo "note: $PREFIX/bin is not on your PATH" ;;
esac
